Fix creation of Azure source connector config
Pass to Kafka Connect the actual config (built by method `configDef()`)
instead of an empty one (`new ConfigDef()`).

Without this fix the connector does not recognise any config paramater
passed to it and fails to start.

Exception logged at connector startup:
```
May 22 15:25:26 kafkacnct-qle06d-1 kafka-connector[286]: [2025-05-22 15:25:26,732] ERROR [azure-source-connector-byte-array-converter-jh6xw5|task-0] WorkerSourceTask{id=azure-source-connector-byte-array-converter-jh6xw5-0} Task threw an uncaught and unrecoverable excepti>
     org.apache.kafka.common.config.ConfigException: Unknown configuration 'distribution.type'
             at org.apache.kafka.common.config.AbstractConfig.get(AbstractConfig.java:164)
             at org.apache.kafka.common.config.AbstractConfig.getString(AbstractConfig.java:199)
             at io.aiven.kafka.connect.common.config.SourceConfigFragment.getDistributionType(SourceConfigFragment.java:116)
             at io.aiven.kafka.connect.common.config.SourceConfigFragment.validate(SourceConfigFragment.java:92)
             at io.aiven.kafka.connect.common.config.SourceCommonConfig.validate(SourceCommonConfig.java:47)
             at io.aiven.kafka.connect.common.config.SourceCommonConfig.<init>(SourceCommonConfig.java:42)
             at io.aiven.kafka.connect.azure.source.config.AzureBlobSourceConfig.<init>(AzureBlobSourceConfig.java:37)
             at io.aiven.kafka.connect.azure.source.AzureBlobSourceTask.configure(AzureBlobSourceTask.java:54)
             at io.aiven.kafka.connect.common.source.AbstractSourceTask.start(AbstractSourceTask.java:173)
             at org.apache.kafka.connect.runtime.AbstractWorkerSourceTask.initializeAndStart(AbstractWorkerSourceTask.java:278)
             at org.apache.kafka.connect.runtime.WorkerTask.doStart(WorkerTask.java:175)
             at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:224)
             at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:280)
             at org.apache.kafka.connect.runtime.AbstractWorkerSourceTask.run(AbstractWorkerSourceTask.java:78)
             at org.apache.kafka.connect.runtime.isolation.Plugins.lambda$withClassLoader$1(Plugins.java:237)
             at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
             at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
             at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
             at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
             at java.base/java.lang.Thread.run(Thread.java:840)

```